"""Initial

Revision ID: 3389da41164f
Revises: 
Create Date: 2024-02-04 07:05:09.937922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '3389da41164f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    op.drop_table('employees')
    op.drop_table('residents')
    op.drop_table('parkings')
    op.drop_table('appartaments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'cars',
        sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column('gos_number', mysql.TINYTEXT(), nullable=True),
        sa.Column('date_start', mysql.DATETIME(), nullable=True),
        sa.Column('date_end', mysql.DATETIME(), nullable=True),
        sa.Column(
            'employee_id', mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'resident_id', mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.ForeignKeyConstraint(
            ['employee_id'], ['employees.id'], name='cars_ibfk_1'
        ),
        sa.ForeignKeyConstraint(
            ['resident_id'], ['residents.id'], name='cars_ibfk_2'
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB',
    )
    op.create_table(
        'residents',
        sa.Column(
            'apartment_id', mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'parking_id', mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            'tg_user_id', mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('surname', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('patronymic', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('phone_number', mysql.VARCHAR(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ['apartment_id'], ['appartaments.id'], name='residents_ibfk_1'
        ),
        sa.ForeignKeyConstraint(
            ['parking_id'], ['parkings.id'], name='residents_ibfk_2'
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB',
    )
    op.create_table(
        'appartaments',
        sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            'number_appartament',
            mysql.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'padik', mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB',
    )
    op.create_table(
        'parkings',
        sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            'number_place', mysql.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'is_busy',
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB',
    )
    op.create_table(
        'employees',
        sa.Column('login', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('password_hash', mysql.VARCHAR(length=255), nullable=True),
        sa.Column(
            'is_admin',
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            'apartment_id', mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column(
            'parking_id', mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
        sa.Column(
            'tg_user_id', mysql.BIGINT(), autoincrement=False, nullable=True
        ),
        sa.Column('name', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('surname', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('patronymic', mysql.VARCHAR(length=255), nullable=True),
        sa.Column('phone_number', mysql.VARCHAR(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ['apartment_id'], ['appartaments.id'], name='employees_ibfk_1'
        ),
        sa.ForeignKeyConstraint(
            ['parking_id'], ['parkings.id'], name='employees_ibfk_2'
        ),
        sa.PrimaryKeyConstraint('id'),
        mysql_collate='utf8mb4_0900_ai_ci',
        mysql_default_charset='utf8mb4',
        mysql_engine='InnoDB',
    )
    # ### end Alembic commands ###
